@UdemyMicroservices.yarp_HostAddress = http://localhost:5215


###

POST {{UdemyMicroservices.yarp_HostAddress}}/v1/file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="hello-world.txt"
Content-Type: text/plain

Hello World
------WebKitFormBoundary--
###
DELETE {{UdemyMicroservices.yarp_HostAddress}}v1/file
Content-Type: application/json
{
  "fileName": "1420a437-2927-47fa-98f7-331a3b877cf0.txt"
}
###
