@UdemyMicroservices.Yarp_HostAddress = http://localhost:5215

POST {{UdemyMicroservices.Yarp_HostAddress}}/v1/payment/receive
Content-Type: application/json
Accept: application/json

{
  "orderCode": "1",
  "cardNumber": "4242 4242 4242 4242",
  "cardHolderName": "ahmet yıldız",
  "expiryDate": "10/24",
  "cvv": "123",
  "amount": 1000
}
###
GET {{UdemyMicroservices.Yarp_HostAddress}}/v1/payment
Content-Type: application/json
###
