services:
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${username}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${password}
      ME_CONFIG_MONGODB_URL: mongodb://root:Password12@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  redis:
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: Password12*
      HTTP_USER: root
      HTTP_PASSWORD: root
    depend_on :
     - redis

 